global:
  smtp_smarthost: 'smtp.gmail.com:587'
  smtp_from: 'abarna.s272@gmail.com'
  smtp_auth_username: 'abarna.s272@gmail.com'
  smtp_auth_password: ''
  smtp_require_tls: true

route:
  receiver: 'email'

receivers:
  - name: 'email'
    email_configs:
      - to: 'abarna.s272@gmail.com'
